title: FHBig
description: FredHutch Bioinformatics Interest Group

date_format: "%b %-d, %Y"

port: 4444

page_root: /

theme: jekyll-theme-cayman

exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock"]

plugins:
  - jekyll-paginate

paginate: 10
